# Generated by Django 3.2.9 on 2021-11-18 20:34

import App.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('Email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('Username', models.CharField(max_length=32, unique=True)),
                ('Firstname', models.CharField(max_length=32, null=True)),
                ('Lastname', models.CharField(max_length=32, null=True)),
                ('password', models.CharField(max_length=32, null=True)),
                ('Coin', models.PositiveIntegerField(default=0, null=True)),
                ('Dob', models.DateField()),
                ('Chart', models.JSONField(default=App.models.User.charttime)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('SID', models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('Doublecoin', models.BooleanField(default=False, null=True)),
                ('Doublecoin_time', models.DateTimeField(null=True)),
                ('Edit_username', models.BooleanField(default=False, null=True)),
                ('dark_mode', models.BooleanField(default=False)),
                ('ml', models.BooleanField(default=False)),
                ('avatar', models.CharField(max_length=32, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.user')),
            ],
        ),
    ]
